import { formatMinor } from "@/lib/format";

export type ReceiptPdfStatus = "posted" | "pending" | "rejected" | "failed" | string;

export type ReceiptPdfData = {
  txNumber: string;
  status: ReceiptPdfStatus;
  direction: "deposit" | "withdraw" | string;
  amountMinor: number;
  currency: string;
  customerName?: string | null;
  dahabNumber?: string | null;
  accountNumber?: string | null;
  accountName?: string | null;
  channel?: string | null;
  vaultName?: string | null;
  comment?: string | null;
  createdAt?: string | Date | null;
  postedAt?: string | Date | null;
  reason?: string | null;
  systemRef?: string | null;
};

function clean(value: unknown, fallback = "-") {
  const text = String(value ?? "").trim();
  return text || fallback;
}

function formatDate(value: string | Date | null | undefined) {
  if (!value) return "-";
  const d = value instanceof Date ? value : new Date(value);
  return Number.isNaN(d.getTime()) ? "-" : d.toLocaleString();
}

function statusLabel(status: string) {
  const value = clean(status).toLowerCase();
  if (["posted", "approved", "sale"].includes(value)) return "Posted / Approved";
  if (value === "pending") return "Awaiting admin approval";
  if (["rejected", "cancelled", "canceled"].includes(value)) return "Rejected";
  if (value === "failed") return "Failed";
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function buildFilename(data: ReceiptPdfData) {
  const tx = clean(data.txNumber, "transaction").replace(/[^a-z0-9_-]+/gi, "-");
  return `DAHAB-receipt-${tx}.pdf`;
}

function line(doc: any, label: string, value: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setTextColor(86, 75, 45);
  doc.text(label, 48, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(24, 24, 27);
  doc.text(value, 210, y, { maxWidth: 330 });
}

export async function createReceiptPdfBlob(data: ReceiptPdfData) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const status = statusLabel(String(data.status || ""));
  const isDeposit = String(data.direction || "").toLowerCase() === "deposit";
  const amount = formatMinor(Number(data.amountMinor || 0), data.currency || "USD");

  doc.setFillColor(18, 18, 20);
  doc.rect(0, 0, pageWidth, 118, "F");
  doc.setTextColor(212, 175, 55);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("DAHAB", 48, 48);
  doc.setFontSize(11);
  doc.setTextColor(245, 245, 245);
  doc.text("Transaction Receipt", 48, 70);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(180, 180, 180);
  doc.text(`Generated ${new Date().toLocaleString()}`, 48, 90);

  doc.setFillColor(250, 247, 237);
  doc.roundedRect(380, 34, 160, 42, 8, 8, "F");
  doc.setTextColor(86, 75, 45);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("STATUS", 398, 50);
  doc.setFontSize(12);
  doc.text(status, 398, 66, { maxWidth: 124 });

  doc.setTextColor(18, 18, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(`${isDeposit ? "+" : "-"} ${amount}`, 48, 158);
  doc.setFontSize(10);
  doc.setTextColor(110, 110, 115);
  doc.text(`${clean(data.currency)} ${isDeposit ? "cash deposit" : "cash withdrawal"}`, 48, 176);

  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.8);
  doc.line(48, 202, pageWidth - 48, 202);

  let y = 235;
  const rows: Array<[string, string]> = [
    ["Transaction #", clean(data.txNumber)],
    ["Created", formatDate(data.createdAt)],
    ["Posted / reviewed", formatDate(data.postedAt)],
    ["Type", isDeposit ? "Deposit" : "Withdrawal"],
    ["Customer", clean(data.customerName)],
    ["DAHAB #", clean(data.dahabNumber)],
    ["Account", [data.accountNumber, data.accountName].map((v) => clean(v, "")).filter(Boolean).join(" - ") || "-"],
    ["Vault / channel", [data.vaultName, data.channel].map((v) => clean(v, "")).filter(Boolean).join(" - ") || "-"],
    ["Comment", clean(data.comment)],
  ];

  if (data.reason) rows.push(["Review / rejection note", clean(data.reason)]);
  if (data.systemRef && data.systemRef !== data.txNumber) rows.push(["System reference", clean(data.systemRef)]);

  for (const [label, value] of rows) {
    line(doc, label, value, y);
    y += 28;
  }

  doc.setDrawColor(230, 224, 205);
  doc.line(48, pageHeight - 82, pageWidth - 48, pageHeight - 82);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 125);
  doc.text("This receipt is generated by DAHAB back-office. Final settlement depends on the displayed status.", 48, pageHeight - 58, {
    maxWidth: pageWidth - 96,
  });

  return doc.output("blob") as Blob;
}

export async function shareReceiptPdf(data: ReceiptPdfData) {
  const blob = await createReceiptPdfBlob(data);
  const filename = buildFilename(data);
  const file = new File([blob], filename, { type: "application/pdf" });
  const nav = navigator as Navigator & {
    canShare?: (data: ShareData & { files?: File[] }) => boolean;
    share?: (data: ShareData & { files?: File[] }) => Promise<void>;
  };

  if (nav.canShare?.({ files: [file] }) && nav.share) {
    await nav.share({
      title: "DAHAB Transaction Receipt",
      text: `DAHAB receipt ${data.txNumber}`,
      files: [file],
    });
    return { shared: true, downloaded: false };
  }

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 2500);
  return { shared: false, downloaded: true };
}
