/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MRouteImport } from './routes/m'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MLoginRouteImport } from './routes/m.login'
import { Route as MDashboardRouteImport } from './routes/m.dashboard'
import { Route as AppVaultsRouteImport } from './routes/app.vaults'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPortalAccountsRouteImport } from './routes/app.portal-accounts'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AppVaultsIndexRouteImport } from './routes/app.vaults.index'
import { Route as AppTransactionsIndexRouteImport } from './routes/app.transactions.index'
import { Route as AppHoldersIndexRouteImport } from './routes/app.holders.index'
import { Route as AppGroupsIndexRouteImport } from './routes/app.groups.index'
import { Route as AppAccountsIndexRouteImport } from './routes/app.accounts.index'
import { Route as PortalAccountIdCurrencyRouteImport } from './routes/portal.$accountId.$currency'
import { Route as AppVaultsIdRouteImport } from './routes/app.vaults.$id'
import { Route as AppUsersNewConsumerRouteImport } from './routes/app.users.new-consumer'
import { Route as AppUsersNewRouteImport } from './routes/app.users.new'
import { Route as AppTransactionsIdRouteImport } from './routes/app.transactions.$id'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppMeActivityRouteImport } from './routes/app.me.activity'
import { Route as AppHoldersNewRouteImport } from './routes/app.holders.new'
import { Route as AppHoldersIdRouteImport } from './routes/app.holders.$id'
import { Route as AppGroupsIdRouteImport } from './routes/app.groups.$id'
import { Route as AppAdminTestSandboxRouteImport } from './routes/app.admin.test-sandbox'
import { Route as AppAdminSandboxWorkspaceRouteImport } from './routes/app.admin.sandbox-workspace'
import { Route as AppAdminSandboxMultiTransactionRouteImport } from './routes/app.admin.sandbox-multi-transaction'
import { Route as AppAdminSandboxMultiEntryRouteImport } from './routes/app.admin.sandbox-multi-entry'
import { Route as AppAdminFxRatesRouteImport } from './routes/app.admin.fx-rates'
import { Route as AppAdminBranchesRouteImport } from './routes/app.admin.branches'
import { Route as AppAccountsIdRouteImport } from './routes/app.accounts.$id'
import { Route as AppTransactionsNewIndexRouteImport } from './routes/app.transactions.new.index'
import { Route as AppTransactionsNewWithdrawRouteImport } from './routes/app.transactions.new.withdraw'
import { Route as AppTransactionsNewDepositRouteImport } from './routes/app.transactions.new.deposit'
import { Route as ApiPublicHooksNotificationsTickRouteImport } from './routes/api/public/hooks/notifications-tick'
import { Route as ApiPublicAdminSeedDemoRouteImport } from './routes/api/public/admin/seed-demo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MLoginRoute = MLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MRoute,
} as any)
const MDashboardRoute = MDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MRoute,
} as any)
const AppVaultsRoute = AppVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalAccountsRoute = AppPortalAccountsRouteImport.update({
  id: '/portal-accounts',
  path: '/portal-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultsRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldersIndexRoute = AppHoldersIndexRouteImport.update({
  id: '/holders/',
  path: '/holders/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const PortalAccountIdCurrencyRoute = PortalAccountIdCurrencyRouteImport.update({
  id: '/$accountId/$currency',
  path: '/$accountId/$currency',
  getParentRoute: () => PortalRoute,
} as any)
const AppVaultsIdRoute = AppVaultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVaultsRoute,
} as any)
const AppUsersNewConsumerRoute = AppUsersNewConsumerRouteImport.update({
  id: '/new-consumer',
  path: '/new-consumer',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppMeActivityRoute = AppMeActivityRouteImport.update({
  id: '/me/activity',
  path: '/me/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldersNewRoute = AppHoldersNewRouteImport.update({
  id: '/holders/new',
  path: '/holders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldersIdRoute = AppHoldersIdRouteImport.update({
  id: '/holders/$id',
  path: '/holders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTestSandboxRoute = AppAdminTestSandboxRouteImport.update({
  id: '/admin/test-sandbox',
  path: '/admin/test-sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSandboxWorkspaceRoute =
  AppAdminSandboxWorkspaceRouteImport.update({
    id: '/admin/sandbox-workspace',
    path: '/admin/sandbox-workspace',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSandboxMultiTransactionRoute =
  AppAdminSandboxMultiTransactionRouteImport.update({
    id: '/admin/sandbox-multi-transaction',
    path: '/admin/sandbox-multi-transaction',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSandboxMultiEntryRoute =
  AppAdminSandboxMultiEntryRouteImport.update({
    id: '/admin/sandbox-multi-entry',
    path: '/admin/sandbox-multi-entry',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminFxRatesRoute = AppAdminFxRatesRouteImport.update({
  id: '/admin/fx-rates',
  path: '/admin/fx-rates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewIndexRoute = AppTransactionsNewIndexRouteImport.update({
  id: '/transactions/new/',
  path: '/transactions/new/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewWithdrawRoute =
  AppTransactionsNewWithdrawRouteImport.update({
    id: '/transactions/new/withdraw',
    path: '/transactions/new/withdraw',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransactionsNewDepositRoute =
  AppTransactionsNewDepositRouteImport.update({
    id: '/transactions/new/deposit',
    path: '/transactions/new/deposit',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksNotificationsTickRoute =
  ApiPublicHooksNotificationsTickRouteImport.update({
    id: '/api/public/hooks/notifications-tick',
    path: '/api/public/hooks/notifications-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSeedDemoRoute = ApiPublicAdminSeedDemoRouteImport.update({
  id: '/api/public/admin/seed-demo',
  path: '/api/public/admin/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/portal-accounts': typeof AppPortalAccountsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/vaults': typeof AppVaultsRouteWithChildren
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app/': typeof AppIndexRoute
  '/m/': typeof MIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/fx-rates': typeof AppAdminFxRatesRoute
  '/app/admin/sandbox-multi-entry': typeof AppAdminSandboxMultiEntryRoute
  '/app/admin/sandbox-multi-transaction': typeof AppAdminSandboxMultiTransactionRoute
  '/app/admin/sandbox-workspace': typeof AppAdminSandboxWorkspaceRoute
  '/app/admin/test-sandbox': typeof AppAdminTestSandboxRoute
  '/app/groups/$id': typeof AppGroupsIdRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/holders/new': typeof AppHoldersNewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/users/new-consumer': typeof AppUsersNewConsumerRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/holders/': typeof AppHoldersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
  '/app/vaults/': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new/': typeof AppTransactionsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/portal-accounts': typeof AppPortalAccountsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app': typeof AppIndexRoute
  '/m': typeof MIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/fx-rates': typeof AppAdminFxRatesRoute
  '/app/admin/sandbox-multi-entry': typeof AppAdminSandboxMultiEntryRoute
  '/app/admin/sandbox-multi-transaction': typeof AppAdminSandboxMultiTransactionRoute
  '/app/admin/sandbox-workspace': typeof AppAdminSandboxWorkspaceRoute
  '/app/admin/test-sandbox': typeof AppAdminTestSandboxRoute
  '/app/groups/$id': typeof AppGroupsIdRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/holders/new': typeof AppHoldersNewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/users/new-consumer': typeof AppUsersNewConsumerRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/accounts': typeof AppAccountsIndexRoute
  '/app/groups': typeof AppGroupsIndexRoute
  '/app/holders': typeof AppHoldersIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
  '/app/vaults': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new': typeof AppTransactionsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/portal-accounts': typeof AppPortalAccountsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/vaults': typeof AppVaultsRouteWithChildren
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app/': typeof AppIndexRoute
  '/m/': typeof MIndexRoute
  '/app/accounts/$id': typeof AppAccountsIdRoute
  '/app/admin/branches': typeof AppAdminBranchesRoute
  '/app/admin/fx-rates': typeof AppAdminFxRatesRoute
  '/app/admin/sandbox-multi-entry': typeof AppAdminSandboxMultiEntryRoute
  '/app/admin/sandbox-multi-transaction': typeof AppAdminSandboxMultiTransactionRoute
  '/app/admin/sandbox-workspace': typeof AppAdminSandboxWorkspaceRoute
  '/app/admin/test-sandbox': typeof AppAdminTestSandboxRoute
  '/app/groups/$id': typeof AppGroupsIdRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/holders/new': typeof AppHoldersNewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/users/new-consumer': typeof AppUsersNewConsumerRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/holders/': typeof AppHoldersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
  '/app/vaults/': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new/': typeof AppTransactionsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/m'
    | '/portal'
    | '/reset-password'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/portal-accounts'
    | '/app/reports'
    | '/app/users'
    | '/app/vaults'
    | '/m/dashboard'
    | '/m/login'
    | '/app/'
    | '/m/'
    | '/app/accounts/$id'
    | '/app/admin/branches'
    | '/app/admin/fx-rates'
    | '/app/admin/sandbox-multi-entry'
    | '/app/admin/sandbox-multi-transaction'
    | '/app/admin/sandbox-workspace'
    | '/app/admin/test-sandbox'
    | '/app/groups/$id'
    | '/app/holders/$id'
    | '/app/holders/new'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/transactions/$id'
    | '/app/users/new'
    | '/app/users/new-consumer'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/accounts/'
    | '/app/groups/'
    | '/app/holders/'
    | '/app/transactions/'
    | '/app/vaults/'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/portal-accounts'
    | '/app/reports'
    | '/app/users'
    | '/m/dashboard'
    | '/m/login'
    | '/app'
    | '/m'
    | '/app/accounts/$id'
    | '/app/admin/branches'
    | '/app/admin/fx-rates'
    | '/app/admin/sandbox-multi-entry'
    | '/app/admin/sandbox-multi-transaction'
    | '/app/admin/sandbox-workspace'
    | '/app/admin/test-sandbox'
    | '/app/groups/$id'
    | '/app/holders/$id'
    | '/app/holders/new'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/transactions/$id'
    | '/app/users/new'
    | '/app/users/new-consumer'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/accounts'
    | '/app/groups'
    | '/app/holders'
    | '/app/transactions'
    | '/app/vaults'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/m'
    | '/portal'
    | '/reset-password'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/portal-accounts'
    | '/app/reports'
    | '/app/users'
    | '/app/vaults'
    | '/m/dashboard'
    | '/m/login'
    | '/app/'
    | '/m/'
    | '/app/accounts/$id'
    | '/app/admin/branches'
    | '/app/admin/fx-rates'
    | '/app/admin/sandbox-multi-entry'
    | '/app/admin/sandbox-multi-transaction'
    | '/app/admin/sandbox-workspace'
    | '/app/admin/test-sandbox'
    | '/app/groups/$id'
    | '/app/holders/$id'
    | '/app/holders/new'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/settings/security'
    | '/app/transactions/$id'
    | '/app/users/new'
    | '/app/users/new-consumer'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/accounts/'
    | '/app/groups/'
    | '/app/holders/'
    | '/app/transactions/'
    | '/app/vaults/'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MRoute: typeof MRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAdminSeedDemoRoute: typeof ApiPublicAdminSeedDemoRoute
  ApiPublicHooksNotificationsTickRoute: typeof ApiPublicHooksNotificationsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/login': {
      id: '/m/login'
      path: '/login'
      fullPath: '/m/login'
      preLoaderRoute: typeof MLoginRouteImport
      parentRoute: typeof MRoute
    }
    '/m/dashboard': {
      id: '/m/dashboard'
      path: '/dashboard'
      fullPath: '/m/dashboard'
      preLoaderRoute: typeof MDashboardRouteImport
      parentRoute: typeof MRoute
    }
    '/app/vaults': {
      id: '/app/vaults'
      path: '/vaults'
      fullPath: '/app/vaults'
      preLoaderRoute: typeof AppVaultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal-accounts': {
      id: '/app/portal-accounts'
      path: '/portal-accounts'
      fullPath: '/app/portal-accounts'
      preLoaderRoute: typeof AppPortalAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vaults/': {
      id: '/app/vaults/'
      path: '/'
      fullPath: '/app/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppVaultsRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/transactions'
      fullPath: '/app/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holders/': {
      id: '/app/holders/'
      path: '/holders'
      fullPath: '/app/holders/'
      preLoaderRoute: typeof AppHoldersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/': {
      id: '/app/groups/'
      path: '/groups'
      fullPath: '/app/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts/': {
      id: '/app/accounts/'
      path: '/accounts'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$accountId/$currency': {
      id: '/portal/$accountId/$currency'
      path: '/$accountId/$currency'
      fullPath: '/portal/$accountId/$currency'
      preLoaderRoute: typeof PortalAccountIdCurrencyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/vaults/$id': {
      id: '/app/vaults/$id'
      path: '/$id'
      fullPath: '/app/vaults/$id'
      preLoaderRoute: typeof AppVaultsIdRouteImport
      parentRoute: typeof AppVaultsRoute
    }
    '/app/users/new-consumer': {
      id: '/app/users/new-consumer'
      path: '/new-consumer'
      fullPath: '/app/users/new-consumer'
      preLoaderRoute: typeof AppUsersNewConsumerRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/users/new': {
      id: '/app/users/new'
      path: '/new'
      fullPath: '/app/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/transactions/$id': {
      id: '/app/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/app/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/settings/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/activity': {
      id: '/app/me/activity'
      path: '/me/activity'
      fullPath: '/app/me/activity'
      preLoaderRoute: typeof AppMeActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holders/new': {
      id: '/app/holders/new'
      path: '/holders/new'
      fullPath: '/app/holders/new'
      preLoaderRoute: typeof AppHoldersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holders/$id': {
      id: '/app/holders/$id'
      path: '/holders/$id'
      fullPath: '/app/holders/$id'
      preLoaderRoute: typeof AppHoldersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups/$id': {
      id: '/app/groups/$id'
      path: '/groups/$id'
      fullPath: '/app/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/test-sandbox': {
      id: '/app/admin/test-sandbox'
      path: '/admin/test-sandbox'
      fullPath: '/app/admin/test-sandbox'
      preLoaderRoute: typeof AppAdminTestSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/sandbox-workspace': {
      id: '/app/admin/sandbox-workspace'
      path: '/admin/sandbox-workspace'
      fullPath: '/app/admin/sandbox-workspace'
      preLoaderRoute: typeof AppAdminSandboxWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/sandbox-multi-transaction': {
      id: '/app/admin/sandbox-multi-transaction'
      path: '/admin/sandbox-multi-transaction'
      fullPath: '/app/admin/sandbox-multi-transaction'
      preLoaderRoute: typeof AppAdminSandboxMultiTransactionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/sandbox-multi-entry': {
      id: '/app/admin/sandbox-multi-entry'
      path: '/admin/sandbox-multi-entry'
      fullPath: '/app/admin/sandbox-multi-entry'
      preLoaderRoute: typeof AppAdminSandboxMultiEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/fx-rates': {
      id: '/app/admin/fx-rates'
      path: '/admin/fx-rates'
      fullPath: '/app/admin/fx-rates'
      preLoaderRoute: typeof AppAdminFxRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/branches': {
      id: '/app/admin/branches'
      path: '/admin/branches'
      fullPath: '/app/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts/$id': {
      id: '/app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/app/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/': {
      id: '/app/transactions/new/'
      path: '/transactions/new'
      fullPath: '/app/transactions/new/'
      preLoaderRoute: typeof AppTransactionsNewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/withdraw': {
      id: '/app/transactions/new/withdraw'
      path: '/transactions/new/withdraw'
      fullPath: '/app/transactions/new/withdraw'
      preLoaderRoute: typeof AppTransactionsNewWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/deposit': {
      id: '/app/transactions/new/deposit'
      path: '/transactions/new/deposit'
      fullPath: '/app/transactions/new/deposit'
      preLoaderRoute: typeof AppTransactionsNewDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/notifications-tick': {
      id: '/api/public/hooks/notifications-tick'
      path: '/api/public/hooks/notifications-tick'
      fullPath: '/api/public/hooks/notifications-tick'
      preLoaderRoute: typeof ApiPublicHooksNotificationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/seed-demo': {
      id: '/api/public/admin/seed-demo'
      path: '/api/public/admin/seed-demo'
      fullPath: '/api/public/admin/seed-demo'
      preLoaderRoute: typeof ApiPublicAdminSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppUsersNewConsumerRoute: typeof AppUsersNewConsumerRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersNewRoute: AppUsersNewRoute,
  AppUsersNewConsumerRoute: AppUsersNewConsumerRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppVaultsRouteChildren {
  AppVaultsIdRoute: typeof AppVaultsIdRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
}

const AppVaultsRouteChildren: AppVaultsRouteChildren = {
  AppVaultsIdRoute: AppVaultsIdRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
}

const AppVaultsRouteWithChildren = AppVaultsRoute._addFileChildren(
  AppVaultsRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppPortalAccountsRoute: typeof AppPortalAccountsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppVaultsRoute: typeof AppVaultsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminFxRatesRoute: typeof AppAdminFxRatesRoute
  AppAdminSandboxMultiEntryRoute: typeof AppAdminSandboxMultiEntryRoute
  AppAdminSandboxMultiTransactionRoute: typeof AppAdminSandboxMultiTransactionRoute
  AppAdminSandboxWorkspaceRoute: typeof AppAdminSandboxWorkspaceRoute
  AppAdminTestSandboxRoute: typeof AppAdminTestSandboxRoute
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppHoldersIdRoute: typeof AppHoldersIdRoute
  AppHoldersNewRoute: typeof AppHoldersNewRoute
  AppMeActivityRoute: typeof AppMeActivityRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppHoldersIndexRoute: typeof AppHoldersIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransactionsNewDepositRoute: typeof AppTransactionsNewDepositRoute
  AppTransactionsNewWithdrawRoute: typeof AppTransactionsNewWithdrawRoute
  AppTransactionsNewIndexRoute: typeof AppTransactionsNewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppPortalAccountsRoute: AppPortalAccountsRoute,
  AppReportsRoute: AppReportsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppVaultsRoute: AppVaultsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminFxRatesRoute: AppAdminFxRatesRoute,
  AppAdminSandboxMultiEntryRoute: AppAdminSandboxMultiEntryRoute,
  AppAdminSandboxMultiTransactionRoute: AppAdminSandboxMultiTransactionRoute,
  AppAdminSandboxWorkspaceRoute: AppAdminSandboxWorkspaceRoute,
  AppAdminTestSandboxRoute: AppAdminTestSandboxRoute,
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppHoldersIdRoute: AppHoldersIdRoute,
  AppHoldersNewRoute: AppHoldersNewRoute,
  AppMeActivityRoute: AppMeActivityRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppTransactionsIdRoute: AppTransactionsIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppHoldersIndexRoute: AppHoldersIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransactionsNewDepositRoute: AppTransactionsNewDepositRoute,
  AppTransactionsNewWithdrawRoute: AppTransactionsNewWithdrawRoute,
  AppTransactionsNewIndexRoute: AppTransactionsNewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MRouteChildren {
  MDashboardRoute: typeof MDashboardRoute
  MLoginRoute: typeof MLoginRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MDashboardRoute: MDashboardRoute,
  MLoginRoute: MLoginRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface PortalRouteChildren {
  PortalAccountIdCurrencyRoute: typeof PortalAccountIdCurrencyRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountIdCurrencyRoute: PortalAccountIdCurrencyRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MRoute: MRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAdminSeedDemoRoute: ApiPublicAdminSeedDemoRoute,
  ApiPublicHooksNotificationsTickRoute: ApiPublicHooksNotificationsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
