/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MRouteImport } from './routes/m'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MLoginRouteImport } from './routes/m.login'
import { Route as MDashboardRouteImport } from './routes/m.dashboard'
import { Route as AppVaultsRouteImport } from './routes/app.vaults'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AppVaultsIndexRouteImport } from './routes/app.vaults.index'
import { Route as AppTransactionsIndexRouteImport } from './routes/app.transactions.index'
import { Route as AppHoldersIndexRouteImport } from './routes/app.holders.index'
import { Route as PortalAccountIdCurrencyRouteImport } from './routes/portal.$accountId.$currency'
import { Route as AppVaultsIdRouteImport } from './routes/app.vaults.$id'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppMeActivityRouteImport } from './routes/app.me.activity'
import { Route as AppImportReviewRouteImport } from './routes/app.import.review'
import { Route as AppHoldersIdRouteImport } from './routes/app.holders.$id'
import { Route as AppTransactionsNewIndexRouteImport } from './routes/app.transactions.new.index'
import { Route as AppTransactionsNewWithdrawRouteImport } from './routes/app.transactions.new.withdraw'
import { Route as AppTransactionsNewDepositRouteImport } from './routes/app.transactions.new.deposit'
import { Route as ApiPublicHooksNotificationsTickRouteImport } from './routes/api/public/hooks/notifications-tick'
import { Route as ApiPublicAdminSeedDemoRouteImport } from './routes/api/public/admin/seed-demo'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MLoginRoute = MLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MRoute,
} as any)
const MDashboardRoute = MDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MRoute,
} as any)
const AppVaultsRoute = AppVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVaultsRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldersIndexRoute = AppHoldersIndexRouteImport.update({
  id: '/holders/',
  path: '/holders/',
  getParentRoute: () => AppRoute,
} as any)
const PortalAccountIdCurrencyRoute = PortalAccountIdCurrencyRouteImport.update({
  id: '/$accountId/$currency',
  path: '/$accountId/$currency',
  getParentRoute: () => PortalRoute,
} as any)
const AppVaultsIdRoute = AppVaultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVaultsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppMeActivityRoute = AppMeActivityRouteImport.update({
  id: '/me/activity',
  path: '/me/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppImportReviewRoute = AppImportReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppImportRoute,
} as any)
const AppHoldersIdRoute = AppHoldersIdRouteImport.update({
  id: '/holders/$id',
  path: '/holders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewIndexRoute = AppTransactionsNewIndexRouteImport.update({
  id: '/transactions/new/',
  path: '/transactions/new/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewWithdrawRoute =
  AppTransactionsNewWithdrawRouteImport.update({
    id: '/transactions/new/withdraw',
    path: '/transactions/new/withdraw',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransactionsNewDepositRoute =
  AppTransactionsNewDepositRouteImport.update({
    id: '/transactions/new/deposit',
    path: '/transactions/new/deposit',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksNotificationsTickRoute =
  ApiPublicHooksNotificationsTickRouteImport.update({
    id: '/api/public/hooks/notifications-tick',
    path: '/api/public/hooks/notifications-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSeedDemoRoute = ApiPublicAdminSeedDemoRouteImport.update({
  id: '/api/public/admin/seed-demo',
  path: '/api/public/admin/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/vaults': typeof AppVaultsRouteWithChildren
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app/': typeof AppIndexRoute
  '/m/': typeof MIndexRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/import/review': typeof AppImportReviewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/holders/': typeof AppHoldersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
  '/app/vaults/': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new/': typeof AppTransactionsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app': typeof AppIndexRoute
  '/m': typeof MIndexRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/import/review': typeof AppImportReviewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/holders': typeof AppHoldersIndexRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
  '/app/vaults': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new': typeof AppTransactionsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/vaults': typeof AppVaultsRouteWithChildren
  '/m/dashboard': typeof MDashboardRoute
  '/m/login': typeof MLoginRoute
  '/app/': typeof AppIndexRoute
  '/m/': typeof MIndexRoute
  '/app/holders/$id': typeof AppHoldersIdRoute
  '/app/import/review': typeof AppImportReviewRoute
  '/app/me/activity': typeof AppMeActivityRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/vaults/$id': typeof AppVaultsIdRoute
  '/portal/$accountId/$currency': typeof PortalAccountIdCurrencyRoute
  '/app/holders/': typeof AppHoldersIndexRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
  '/app/vaults/': typeof AppVaultsIndexRoute
  '/api/public/admin/seed-demo': typeof ApiPublicAdminSeedDemoRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/app/transactions/new/deposit': typeof AppTransactionsNewDepositRoute
  '/app/transactions/new/withdraw': typeof AppTransactionsNewWithdrawRoute
  '/app/transactions/new/': typeof AppTransactionsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/m'
    | '/portal'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/import'
    | '/app/users'
    | '/app/vaults'
    | '/m/dashboard'
    | '/m/login'
    | '/app/'
    | '/m/'
    | '/app/holders/$id'
    | '/app/import/review'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/holders/'
    | '/app/transactions/'
    | '/app/vaults/'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/import'
    | '/app/users'
    | '/m/dashboard'
    | '/m/login'
    | '/app'
    | '/m'
    | '/app/holders/$id'
    | '/app/import/review'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/holders'
    | '/app/transactions'
    | '/app/vaults'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/m'
    | '/portal'
    | '/app/about'
    | '/app/approvals'
    | '/app/audit'
    | '/app/import'
    | '/app/users'
    | '/app/vaults'
    | '/m/dashboard'
    | '/m/login'
    | '/app/'
    | '/m/'
    | '/app/holders/$id'
    | '/app/import/review'
    | '/app/me/activity'
    | '/app/settings/notifications'
    | '/app/vaults/$id'
    | '/portal/$accountId/$currency'
    | '/app/holders/'
    | '/app/transactions/'
    | '/app/vaults/'
    | '/api/public/admin/seed-demo'
    | '/api/public/hooks/notifications-tick'
    | '/app/transactions/new/deposit'
    | '/app/transactions/new/withdraw'
    | '/app/transactions/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MRoute: typeof MRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ApiPublicAdminSeedDemoRoute: typeof ApiPublicAdminSeedDemoRoute
  ApiPublicHooksNotificationsTickRoute: typeof ApiPublicHooksNotificationsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/login': {
      id: '/m/login'
      path: '/login'
      fullPath: '/m/login'
      preLoaderRoute: typeof MLoginRouteImport
      parentRoute: typeof MRoute
    }
    '/m/dashboard': {
      id: '/m/dashboard'
      path: '/dashboard'
      fullPath: '/m/dashboard'
      preLoaderRoute: typeof MDashboardRouteImport
      parentRoute: typeof MRoute
    }
    '/app/vaults': {
      id: '/app/vaults'
      path: '/vaults'
      fullPath: '/app/vaults'
      preLoaderRoute: typeof AppVaultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vaults/': {
      id: '/app/vaults/'
      path: '/'
      fullPath: '/app/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppVaultsRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/transactions'
      fullPath: '/app/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holders/': {
      id: '/app/holders/'
      path: '/holders'
      fullPath: '/app/holders/'
      preLoaderRoute: typeof AppHoldersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/$accountId/$currency': {
      id: '/portal/$accountId/$currency'
      path: '/$accountId/$currency'
      fullPath: '/portal/$accountId/$currency'
      preLoaderRoute: typeof PortalAccountIdCurrencyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/vaults/$id': {
      id: '/app/vaults/$id'
      path: '/$id'
      fullPath: '/app/vaults/$id'
      preLoaderRoute: typeof AppVaultsIdRouteImport
      parentRoute: typeof AppVaultsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me/activity': {
      id: '/app/me/activity'
      path: '/me/activity'
      fullPath: '/app/me/activity'
      preLoaderRoute: typeof AppMeActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import/review': {
      id: '/app/import/review'
      path: '/review'
      fullPath: '/app/import/review'
      preLoaderRoute: typeof AppImportReviewRouteImport
      parentRoute: typeof AppImportRoute
    }
    '/app/holders/$id': {
      id: '/app/holders/$id'
      path: '/holders/$id'
      fullPath: '/app/holders/$id'
      preLoaderRoute: typeof AppHoldersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/': {
      id: '/app/transactions/new/'
      path: '/transactions/new'
      fullPath: '/app/transactions/new/'
      preLoaderRoute: typeof AppTransactionsNewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/withdraw': {
      id: '/app/transactions/new/withdraw'
      path: '/transactions/new/withdraw'
      fullPath: '/app/transactions/new/withdraw'
      preLoaderRoute: typeof AppTransactionsNewWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/new/deposit': {
      id: '/app/transactions/new/deposit'
      path: '/transactions/new/deposit'
      fullPath: '/app/transactions/new/deposit'
      preLoaderRoute: typeof AppTransactionsNewDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/notifications-tick': {
      id: '/api/public/hooks/notifications-tick'
      path: '/api/public/hooks/notifications-tick'
      fullPath: '/api/public/hooks/notifications-tick'
      preLoaderRoute: typeof ApiPublicHooksNotificationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/seed-demo': {
      id: '/api/public/admin/seed-demo'
      path: '/api/public/admin/seed-demo'
      fullPath: '/api/public/admin/seed-demo'
      preLoaderRoute: typeof ApiPublicAdminSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppImportRouteChildren {
  AppImportReviewRoute: typeof AppImportReviewRoute
}

const AppImportRouteChildren: AppImportRouteChildren = {
  AppImportReviewRoute: AppImportReviewRoute,
}

const AppImportRouteWithChildren = AppImportRoute._addFileChildren(
  AppImportRouteChildren,
)

interface AppVaultsRouteChildren {
  AppVaultsIdRoute: typeof AppVaultsIdRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
}

const AppVaultsRouteChildren: AppVaultsRouteChildren = {
  AppVaultsIdRoute: AppVaultsIdRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
}

const AppVaultsRouteWithChildren = AppVaultsRoute._addFileChildren(
  AppVaultsRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppImportRoute: typeof AppImportRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppVaultsRoute: typeof AppVaultsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppHoldersIdRoute: typeof AppHoldersIdRoute
  AppMeActivityRoute: typeof AppMeActivityRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppHoldersIndexRoute: typeof AppHoldersIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransactionsNewDepositRoute: typeof AppTransactionsNewDepositRoute
  AppTransactionsNewWithdrawRoute: typeof AppTransactionsNewWithdrawRoute
  AppTransactionsNewIndexRoute: typeof AppTransactionsNewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppImportRoute: AppImportRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppVaultsRoute: AppVaultsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppHoldersIdRoute: AppHoldersIdRoute,
  AppMeActivityRoute: AppMeActivityRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppHoldersIndexRoute: AppHoldersIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransactionsNewDepositRoute: AppTransactionsNewDepositRoute,
  AppTransactionsNewWithdrawRoute: AppTransactionsNewWithdrawRoute,
  AppTransactionsNewIndexRoute: AppTransactionsNewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MRouteChildren {
  MDashboardRoute: typeof MDashboardRoute
  MLoginRoute: typeof MLoginRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MDashboardRoute: MDashboardRoute,
  MLoginRoute: MLoginRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface PortalRouteChildren {
  PortalAccountIdCurrencyRoute: typeof PortalAccountIdCurrencyRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountIdCurrencyRoute: PortalAccountIdCurrencyRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MRoute: MRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ApiPublicAdminSeedDemoRoute: ApiPublicAdminSeedDemoRoute,
  ApiPublicHooksNotificationsTickRoute: ApiPublicHooksNotificationsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
