
CREATE TABLE public.branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  city TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "branches staff read"
  ON public.branches FOR SELECT TO authenticated
  USING (is_staff(auth.uid()));

CREATE POLICY "branches admin write"
  ON public.branches FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER branches_updated_at
  BEFORE UPDATE ON public.branches
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.profiles
  ADD COLUMN branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL;

ALTER TABLE public.transactions
  ADD COLUMN branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL;

CREATE INDEX idx_transactions_branch_id ON public.transactions(branch_id);
CREATE INDEX idx_profiles_branch_id ON public.profiles(branch_id);

CREATE OR REPLACE FUNCTION public.transactions_fill_branch()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.branch_id IS NULL AND NEW.created_by_user_id IS NOT NULL THEN
    SELECT branch_id INTO NEW.branch_id
    FROM public.profiles
    WHERE id = NEW.created_by_user_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER transactions_fill_branch_trg
  BEFORE INSERT ON public.transactions
  FOR EACH ROW EXECUTE FUNCTION public.transactions_fill_branch();
