
-- Holder creation RPCs
CREATE OR REPLACE FUNCTION public.create_holder_with_accounts(
  p_canonical_name text,
  p_holder_type text,
  p_accounts jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_holder_id bigint;
  v_dahab text;
  v_acc jsonb;
  v_count int := 0;
  v_name text := btrim(coalesce(p_canonical_name,''));
BEGIN
  IF NOT public.has_role(v_uid,'admin') THEN RAISE EXCEPTION 'Admin only'; END IF;
  IF length(v_name) < 2 THEN RAISE EXCEPTION 'Holder name is required'; END IF;
  IF p_accounts IS NULL OR jsonb_typeof(p_accounts) <> 'array' OR jsonb_array_length(p_accounts) < 1 THEN
    RAISE EXCEPTION 'At least one linked account is required';
  END IF;

  v_dahab := public.next_dahab_account_number();
  INSERT INTO public.account_holders(dahab_account_number, canonical_name, normalized_name, holder_type)
    VALUES (v_dahab, v_name, lower(v_name), COALESCE(NULLIF(btrim(p_holder_type),''),'INDIVIDUAL'))
    RETURNING id INTO v_holder_id;

  FOR v_acc IN SELECT * FROM jsonb_array_elements(p_accounts) LOOP
    IF COALESCE(btrim(v_acc->>'account_number'),'') = '' THEN
      RAISE EXCEPTION 'Account number is required for every linked account';
    END IF;
    IF COALESCE(btrim(v_acc->>'currency_code'),'') = '' THEN
      RAISE EXCEPTION 'Currency code is required for every linked account';
    END IF;
    INSERT INTO public.holder_accounts(
      account_number, account_holder_id, dahab_account_number, currency_code,
      account_nature, account_display_name, account_alias_name, is_primary_account
    ) VALUES (
      btrim(v_acc->>'account_number'),
      v_holder_id,
      v_dahab,
      upper(btrim(v_acc->>'currency_code')),
      COALESCE(NULLIF(btrim(v_acc->>'account_nature'),''),'Debit'),
      COALESCE(NULLIF(btrim(v_acc->>'account_display_name'),''), v_name),
      NULLIF(btrim(v_acc->>'account_alias_name'),''),
      COALESCE((v_acc->>'is_primary_account')::boolean, false)
    );
    v_count := v_count + 1;
  END LOOP;

  INSERT INTO public.audit_log(actor_user_id, action, target, details)
  VALUES (v_uid, 'holder.create', v_dahab, jsonb_build_object('holder_id', v_holder_id, 'accounts', v_count));

  RETURN jsonb_build_object('holder_id', v_holder_id, 'dahab_account_number', v_dahab, 'accounts_created', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.add_account_to_holder(
  p_holder_id bigint,
  p_account jsonb
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_holder public.account_holders;
  v_id bigint;
BEGIN
  IF NOT public.has_role(v_uid,'admin') THEN RAISE EXCEPTION 'Admin only'; END IF;
  SELECT * INTO v_holder FROM public.account_holders WHERE id = p_holder_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Holder not found'; END IF;
  IF COALESCE(btrim(p_account->>'account_number'),'') = '' THEN
    RAISE EXCEPTION 'Account number is required';
  END IF;
  IF COALESCE(btrim(p_account->>'currency_code'),'') = '' THEN
    RAISE EXCEPTION 'Currency code is required';
  END IF;

  INSERT INTO public.holder_accounts(
    account_number, account_holder_id, dahab_account_number, currency_code,
    account_nature, account_display_name, account_alias_name, is_primary_account
  ) VALUES (
    btrim(p_account->>'account_number'),
    v_holder.id,
    v_holder.dahab_account_number,
    upper(btrim(p_account->>'currency_code')),
    COALESCE(NULLIF(btrim(p_account->>'account_nature'),''),'Debit'),
    COALESCE(NULLIF(btrim(p_account->>'account_display_name'),''), v_holder.canonical_name),
    NULLIF(btrim(p_account->>'account_alias_name'),''),
    COALESCE((p_account->>'is_primary_account')::boolean, false)
  ) RETURNING id INTO v_id;

  INSERT INTO public.audit_log(actor_user_id, action, target, details)
  VALUES (v_uid, 'holder.add_account', v_holder.dahab_account_number, jsonb_build_object('holder_account_id', v_id));

  RETURN v_id;
END;
$$;

-- Account groups
CREATE TABLE IF NOT EXISTS public.account_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.account_group_members (
  group_id bigint NOT NULL REFERENCES public.account_groups(id) ON DELETE CASCADE,
  holder_account_id bigint NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now(),
  added_by uuid,
  PRIMARY KEY (group_id, holder_account_id)
);

CREATE INDEX IF NOT EXISTS account_group_members_account_idx
  ON public.account_group_members(holder_account_id);

ALTER TABLE public.account_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_group_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "groups admin write" ON public.account_groups;
CREATE POLICY "groups admin write" ON public.account_groups
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

DROP POLICY IF EXISTS "groups staff read" ON public.account_groups;
CREATE POLICY "groups staff read" ON public.account_groups
  FOR SELECT TO authenticated
  USING (public.is_staff(auth.uid()));

DROP POLICY IF EXISTS "group_members admin write" ON public.account_group_members;
CREATE POLICY "group_members admin write" ON public.account_group_members
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

DROP POLICY IF EXISTS "group_members staff read" ON public.account_group_members;
CREATE POLICY "group_members staff read" ON public.account_group_members
  FOR SELECT TO authenticated
  USING (public.is_staff(auth.uid()));

-- Per-currency totals across a group: sum of lifetime debits, credits, current balance, account count
CREATE OR REPLACE FUNCTION public.get_group_totals(p_group_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_result jsonb;
BEGIN
  IF NOT public.is_staff(v_uid) THEN RAISE EXCEPTION 'Staff only'; END IF;

  WITH members AS (
    SELECT ha.id, ha.currency_code, ha.current_balance
    FROM public.account_group_members m
    JOIN public.holder_accounts ha ON ha.id = m.holder_account_id
    WHERE m.group_id = p_group_id
  ),
  ledger_sum AS (
    SELECT le.account_id,
           COALESCE(SUM(le.debit_amount),0)  AS d,
           COALESCE(SUM(le.credit_amount),0) AS c
    FROM public.holder_ledger_entries le
    WHERE le.account_id IN (SELECT id FROM members)
    GROUP BY le.account_id
  ),
  per_account AS (
    SELECT m.currency_code,
           COALESCE(ls.d,0)::numeric AS debit_total,
           COALESCE(ls.c,0)::numeric AS credit_total,
           m.current_balance::numeric AS balance
    FROM members m
    LEFT JOIN ledger_sum ls ON ls.account_id = m.id
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'currency', currency_code,
           'total_debits', sum(debit_total),
           'total_credits', sum(credit_total),
           'total_balance', sum(balance),
           'account_count', count(*)
         ) ORDER BY currency_code), '[]'::jsonb)
    INTO v_result
  FROM per_account
  GROUP BY currency_code;

  -- The above only emits one row per currency due to GROUP BY; rewrap properly:
  SELECT COALESCE(jsonb_agg(row_to_json(t) ORDER BY t.currency), '[]'::jsonb)
    INTO v_result
  FROM (
    SELECT currency_code AS currency,
           SUM(debit_total)  AS total_debits,
           SUM(credit_total) AS total_credits,
           SUM(balance)      AS total_balance,
           COUNT(*)          AS account_count
    FROM (
      SELECT m.currency_code,
             COALESCE(ls.d,0)::numeric AS debit_total,
             COALESCE(ls.c,0)::numeric AS credit_total,
             m.current_balance::numeric AS balance
      FROM (
        SELECT ha.id, ha.currency_code, ha.current_balance
        FROM public.account_group_members am
        JOIN public.holder_accounts ha ON ha.id = am.holder_account_id
        WHERE am.group_id = p_group_id
      ) m
      LEFT JOIN (
        SELECT le.account_id,
               SUM(le.debit_amount)  AS d,
               SUM(le.credit_amount) AS c
        FROM public.holder_ledger_entries le
        GROUP BY le.account_id
      ) ls ON ls.account_id = m.id
    ) x
    GROUP BY currency_code
  ) t;

  RETURN v_result;
END;
$$;
